import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#ffb59d",
        "secondary-fixed": "#87f6e0",
        "tertiary": "#ab3600",
        "on-primary-fixed-variant": "#832600",
        "on-background": "#1c1c16",
        "on-error": "#ffffff",
        "outline-variant": "#e1bfb5",
        "primary": "#ab3500",
        "secondary-fixed-dim": "#6ad9c4",
        "tertiary-fixed": "#ffdbcf",
        "secondary": "#006b5d",
        "outline": "#8d7168",
        "on-secondary-fixed-variant": "#005046",
        "background": "#fcf9ef",
        "error": "#ba1a1a",
        "surface-container-low": "#f6f4ea",
        "inverse-on-surface": "#f4f1e7",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#f1eee4",
        "surface-dim": "#dcdad0",
        "surface-container-high": "#ebe8de",
        "surface-tint": "#ab3500",
        "on-primary-fixed": "#390c00",
        "tertiary-fixed-dim": "#ffb59c",
        "surface-bright": "#fcf9ef",
        "tertiary-container": "#fe6c35",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#00201b",
        "surface-variant": "#e5e2d9",
        "primary-container": "#ff6b35",
        "surface-container-highest": "#e5e2d9",
        "on-primary-container": "#5f1900",
        "on-tertiary-container": "#5e1a00",
        "on-tertiary-fixed": "#390c00",
        "on-tertiary-fixed-variant": "#822700",
        "primary-fixed-dim": "#ffb59d",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "on-surface": "#1c1c16",
        "on-surface-variant": "#594139",
        "inverse-surface": "#31312a",
        "on-secondary": "#ffffff",
        "surface": "#fcf9ef",
        "primary-fixed": "#ffdbd0",
        "on-secondary-container": "#007163",
        "secondary-container": "#87f6e0",
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Be Vietnam Pro", "sans-serif"],
        "label": ["Be Vietnam Pro", "sans-serif"],
      },
      backgroundImage: {
        'text-gradient': 'linear-gradient(to right, #ab3500, #ff6b35)',
      }
    },
  },
  plugins: [],
} satisfies Config;
