import json
import os

FILE_PATH = r'c:\Users\Hai\.gemini\antigravity\scratch\nau-gi-day-pwa\src\lib\recipes_data.json'

new_recipes_raw = [
{"id":"ca-chep-001","name":"Cá chép kho tộ","region":"mien-nam","difficulty":"de","ingredients":{"main":"1 con cá chép 500g, 2 muỗng canh nước dừa tươi","optional":"Nước mắm, đường, tiêu, hành tím, ớt hiểm"},"steps":["Làm sạch cá, ướp với nước mắm, đường, tiêu trong 15 phút.","Phi thơm hành tím, xếp cá vào nồi kho nhỏ lửa.","Thêm nước dừa, kho đến khi nước sánh lại, rắc tiêu và ớt lên trên."],"tags":["savory","traditional","home-cooking","caramelized","comfort-food"],"description":"Cá chép kho tộ thấm đẫm gia vị, thịt chắc ngọt hòa quyện cùng nước dừa béo ngậy.","tips":"Nên dùng nồi đất để giữ nhiệt tốt và giúp cá kho thơm ngon hơn. Không đảo cá nhiều để tránh nát.","calories":320,"time":40},
{"id":"ca-chep-002","name":"Cá chép hấp bia","region":"mien-trung","difficulty":"de","ingredients":{"main":"1 con cá chép 600g, 1 lon bia tươi","optional":"Sả, gừng, hành lá, rau răm, nước mắm, muối"},"steps":["Làm sạch cá, khứa nhẹ hai bên thân, ướp muối và sả băm.","Đặt cá lên đĩa, đổ bia ngập nửa thân cá, thêm gừng đập dập.","Hấp cách thủy 20 phút, rắc hành lá và rau răm lên trước khi dùng."],"tags":["steamed","aromatic","light","refreshing","beer-infused"],"description":"Cá chép hấp bia giữ trọn vị ngọt tự nhiên, thịt cá mềm thơm hương bia và gừng nhẹ.","tips":"Không hấp quá lâu để thịt cá không bị bở. Bia giúp khử tanh và làm mềm thịt cá nhanh chóng.","calories":280,"time":30},
{"id":"ca-chep-003","name":"Cá chép nấu canh chua","region":"mien-nam","difficulty":"de","ingredients":{"main":"1 con cá chép 500g, 200g bạc hà, 100g giá đỗ","optional":"Me chua, cà chua, thơm, đường, nước mắm, ngò gai, ớt"},"steps":["Cá làm sạch, cắt khúc, ướp chút muối. Me vắt lấy nước cốt.","Đun sôi nước, thả cá vào nấu chín, vớt bọt.","Cho thơm, cà chua, bạc hà vào, nêm nếm chua ngọt vừa miệng, tắt bếp thêm giá và ngò."],"tags":["sour-soup","refreshing","traditional","light","vegetable-rich"],"description":"Canh chua cá chép thanh mát, vị chua dịu từ me hòa quyện cùng thịt cá ngọt lành.","tips":"Thả rau sống vào sau cùng để giữ độ giòn. Nêm đường nhẹ để cân bằng vị chua gắt.","calories":250,"time":35},
{"id":"ca-chep-004","name":"Cá chép chiên giòn","region":"toan-quoc","difficulty":"trung-binh","ingredients":{"main":"1 con cá chép 600g, 100g bột chiên giòn","optional":"Muối, tiêu, tỏi băm, dầu ăn, tương ớt, chanh"},"steps":["Cá làm sạch, khứa chéo, ướp muối tiêu 10 phút.","Lăn cá qua bột chiên giòn đã pha loãng sệt vừa phải.","Chiên ngập dầu lửa vừa đến khi vàng giòn, vớt ra giấy thấm dầu."],"tags":["crispy","fried","street-food","quick-meal","golden"],"description":"Cá chép chiên giòn rụm bên ngoài, thịt bên trong ẩm mềm, chấm tương ớt cay nhẹ rất đưa cơm.","tips":"Chiên lửa nhỏ trước để cá chín đều, sau đó tăng lửa lớn để vỏ giòn. Dầu nóng già giúp cá không ngấm mỡ.","calories":380,"time":25},
{"id":"ca-chep-005","name":"Cá chép om dưa","region":"mien-bac","difficulty":"trung-binh","ingredients":{"main":"1 con cá chép 500g, 300g dưa cải muối chua","optional":"Thì là, hành lá, mỡ lợn, nước mắm, đường, ớt"},"steps":["Dưa cải rửa sạch, vắt ráo, cắt khúc. Cá ướp gia vị sơ.","Phi thơm mỡ lợn, xào dưa cho săn, đổ nước vừa ăn đun sôi.","Cho cá vào om lửa nhỏ 15 phút, rắc thì là và hành lá."],"tags":["fermented","tangy","northern","comfort-food","savory"],"description":"Cá chép om dưa mang hương vị đặc trưng miền Bắc, vị chua dịu của dưa hòa quyện thịt cá béo ngọt.","tips":"Dùng mỡ lợn xào dưa sẽ thơm hơn dầu ăn. Om nhỏ lửa giúp cá thấm vị mà không nát.","calories":310,"time":45},
{"id":"ca-chep-006","name":"Cháo cá chép","region":"toan-quoc","difficulty":"de","ingredients":{"main":"1 con cá chép 400g, 100g gạo tẻ","optional":"Gừng, hành khô, ngò gai, nước mắm, muối, tiêu, dầu ăn"},"steps":["Nấu gạo thành cháo đặc. Luộc cá chín, gỡ lấy thịt, xương hầm lấy nước trong.","Xào hành khô, gừng với dầu, phi thơm rồi cho thịt cá vào đảo nhẹ.","Đổ thịt cá và nước luộc vào cháo, nêm nếm, rắc hành ngò trước khi ăn."],"tags":["porridge","nutritious","healing","comfort-food","breakfast"],"description":"Cháo cá chép nóng hổi, dễ tiêu hóa, thích hợp cho người mới ốm dậy hoặc trẻ nhỏ.","tips":"Gỡ kỹ xương cá để tránh hóc. Cho gừng vào khử tanh và giữ ấm cơ thể.","calories":260,"time":50},
{"id":"ca-chep-007","name":"Cá chép nướng lá chuối","region":"mien-trung","difficulty":"trung-binh","ingredients":{"main":"1 con cá chép 500g, 2 lá chuối to","optional":"Sả, ớt, ngũ vị hương, nước mắm, đường, dầu ăn"},"steps":["Cá làm sạch, ướp sả ớt băm, ngũ vị hương, nước mắm, đường 20 phút.","Gói cá kín trong lá chuối, buộc chặt bằng dây chuối hoặc lạt.","Nướng trên than hoa hoặc lò 20 phút đến khi lá chuối xém thơm."],"tags":["grilled","aromatic","leaf-wrapped","traditional","smoky"],"description":"Cá nướng lá chuối giữ nguyên độ ẩm, thơm mùi lá chuối cháy xém và gia vị đậm đà.","tips":"Dùng lá chuối tươi sẽ không bị rách khi nướng. Quét thêm dầu lên lá giúp cá không dính.","calories":290,"time":40},
{"id":"ca-chep-008","name":"Cá chép sốt cà chua","region":"mien-bac","difficulty":"de","ingredients":{"main":"1 con cá chép 600g, 3 quả cà chua chín","optional":"Hành tím, tỏi, nước mắm, đường, tương cà, dầu ăn, hành lá"},"steps":["Cá chiên sơ vàng, vớt ra để ráo. Cà chua băm nhuyễn, xào chín nhừ.","Phi thơm hành tỏi, cho cà chua vào đảo, nêm mắm đường.","Cho cá vào rim nhẹ 5 phút, nước sốt sánh lại thì tắt bếp."],"tags":["tomato-sauce","sweet-tangy","home-cooking","colorful","family-meal"],"description":"Cá chép sốt cà chua chua ngọt hài hòa, màu sắc bắt mắt, rất dễ ăn và đưa cơm.","tips":"Xào kỹ cà chua để ra màu đỏ đẹp. Nêm ngọt nhẹ để cân bằng vị chua của cà.","calories":300,"time":35},
{"id":"ca-chep-009","name":"Cá chép hấp nấm hương","region":"toan-quoc","difficulty":"de","ingredients":{"main":"1 con cá chép 500g, 50g nấm hương khô","optional":"Gừng, hành lá, nước tương, dầu mè, tiêu, muối"},"steps":["Nấm hương ngâm mềm, thái sợi. Cá ướp gừng băm, muối, nước tương 15 phút.","Xếp nấm hương lên mặt cá, đặt vào xửng hấp.","Hấp 20 phút, rắc tiêu, hành lá, rưới dầu mè nóng lên trên."],"tags":["steamed","umami","light","mushroom","healthy"],"description":"Cá hấp nấm hương thanh đạm, vị ngọt từ nấm và cá hòa quyện, tốt cho sức khỏe.","tips":"Ngâm nấm trong nước ấm để nấm nở đều và giữ hương. Rưới dầu mè khi vừa tắt bếp để dậy mùi.","calories":270,"time":30},
{"id":"ca-chep-010","name":"Cá chép rim mặn ngọt","region":"mien-nam","difficulty":"de","ingredients":{"main":"1 con cá chép 400g cắt khúc, 2 muỗng đường","optional":"Nước mắm, tiêu, hành tím, nước màu dừa, ớt"},"steps":["Ướp cá với nước mắm, đường, nước màu trong 10 phút.","Phi hành tím, cho cá vào rim lửa nhỏ, trở nhẹ tay.","Khi nước sốt sệt lại, rắc tiêu và ớt, tắt bếp."],"tags":["sweet-savory","glazed","quick","simple","comfort-food"],"description":"Cá rim mặn ngọt bóng bẩy, thấm đều gia vị, ăn kèm cơm nóng rất ngon.","tips":"Dùng nước màu dừa tự nhiên để cá lên màu đẹp và không bị đắng. Rim lửa nhỏ giúp cá không cháy.","calories":310,"time":25},
{"id":"ca-chep-011","name":"Lẩu cá chép","region":"toan-quoc","difficulty":"trung-binh","ingredients":{"main":"1 con cá chép 800g, 500g rau muống, 200g đậu phụ","optional":"Mẻ, mắm tôm, sả, ớt, me chua, bún, nấm kim châm"},"steps":["Cá làm sạch, ướp sả ớt, me chua 15 phút. Nước lẩu hầm xương lợn.","Phi thơm sả, cho nước dùng vào, nêm mẻ và mắm tôm.","Nhúng cá vào lẩu sôi, ăn kèm rau, đậu, bún và nấm."],"tags":["hotpot","communal","spicy","aromatic","social-dining"],"description":"Lẩu cá chép nóng hổi, vị chua cay đặc trưng, thích hợp cho bữa ăn gia đình hoặc tụ tập bạn bè.","tips":"Cho mẻ vào sau khi nước sôi để giữ vị chua thơm. Nhúng cá vừa chín tới để thịt ngọt.","calories":450,"time":60},
{"id":"ca-chep-012","name":"Cá chép xào lăn","region":"mien-bac","difficulty":"trung-binh","ingredients":{"main":"1 con cá chép 500g, 100g dừa tươi nạo","optional":"Sả, gừng, hành tỏi, nghệ, nước cốt dừa, tiêu, rau răm"},"steps":["Cá cắt khúc, ướp nghệ, sả, gừng, tiêu 15 phút.","Phi thơm hành tỏi, xào cá săn, thêm dừa nạo và nước cốt dừa.","Đun nhỏ lửa 10 phút, rắc rau răm, ăn nóng với cơm."],"tags":["coconut","aromatic","stir-fried","northern","rich"],"description":"Cá xào lăn béo ngậy nước cốt dừa, thơm hương sả gừng, vị đậm đà khó cưỡng.","tips":"Dùng dừa tươi nạo sẽ thơm hơn dừa đóng hộp. Xào lửa vừa để cá không vỡ nát.","calories":360,"time":35},
{"id":"ca-chep-013","name":"Cá chép chưng tương","region":"mien-bac","difficulty":"de","ingredients":{"main":"1 con cá chép 500g, 3 muỗng tương bần","optional":"Dứa, gừng, hành khô, ớt, đường, dầu ăn"},"steps":["Cá làm sạch, khứa nhẹ, ướp tương bần và đường 10 phút.","Xếp cá vào đĩa, phủ dứa thái lát, gừng sợi lên trên.","Hấp cách thủy 20 phút, phi hành ớt rưới lên mặt cá."],"tags":["fermented-paste","steamed","tangy","traditional","simple"],"description":"Cá chưng tương bần mang hương vị đặc trưng đồng bằng Bắc Bộ, vị mặn ngọt hài hòa.","tips":"Tương bần đã mặn nên hạn chế thêm mắm muối. Dứa giúp cân bằng vị và khử tanh hiệu quả.","calories":290,"time":30},
{"id":"ca-chep-014","name":"Cá chép cuốn bánh tráng","region":"mien-nam","difficulty":"trung-binh","ingredients":{"main":"1 con cá chép 600g, 200g bánh tráng mỏng","optional":"Rau sống, bún, dưa leo, xà lách, nước mắm pha, tỏi, ớt, chanh"},"steps":["Cá hấp chín, gỡ thịt thành sợi. Tráng bánh mềm, xếp rau, bún, cá lên.","Cuộn chặt tay, chấm nước mắm chua ngọt pha tỏi ớt.","Thưởng thức ngay để bánh tráng không bị khô cứng."],"tags":["fresh","wrapped","light","healthy","street-food"],"description":"Gỏi cuốn cá chép thanh mát, giòn ngọt từ rau sống và cá, chấm mắm nêm hoặc mắm pha đều ngon.","tips":"Rưới chút dầu ăn lên bánh tráng khi cuốn để không dính. Cá hấp xong nên để nguội bớt mới cuốn.","calories":280,"time":25},
{"id":"ca-chep-015","name":"Cá chép chiên nước mắm","region":"mien-nam","difficulty":"de","ingredients":{"main":"1 con cá chép 500g, 4 muỗng nước mắm","optional":"Đường, tỏi băm, ớt, chanh, dầu ăn, tiêu"},"steps":["Cá chiên vàng giòn, vớt ra giấy thấm dầu. Pha nước mắm, đường, tỏi ớt, chanh.","Đun hỗn hợp nước mắm sôi nhẹ, đổ nhanh lên mặt cá.","Rắc tiêu, dùng nóng với cơm trắng."],"tags":["sweet-fish-sauce","crispy","quick","southern","flavorful"],"description":"Cá chiên giòn rụm tưới nước mắm chua ngọt tỏi ớt, thơm lừng, kích thích vị giác.","tips":"Đổ nước mắm khi vừa sôi để tỏi ớt dậy mùi mà không bị cháy. Chiên cá thật khô vỏ để không bị ỉu.","calories":350,"time":30},
{"id":"ca-chep-016","name":"Cá chép hầm thuốc bắc","region":"toan-quoc","difficulty":"kho","ingredients":{"main":"1 con cá chép 600g, gói thuốc bắc (đương quy, kỷ tử, táo đỏ)","optional":"Gừng, nước dừa, muối, tiêu, hành lá, rượu nếp"},"steps":["Cá làm sạch, ướp gừng và rượu 10 phút. Thuốc bắc rửa sạch.","Xếp thuốc bắc vào bụng cá, buộc lạt chặt. Cho vào nồi, đổ nước dừa ngập.","Hầm lửa nhỏ 45 phút, nêm muối nhẹ, rắc hành lá."],"tags":["herbal","nourishing","slow-cooked","medicinal","tonic"],"description":"Cá hầm thuốc bắc bổ dưỡng, thích hợp bồi bổ sức khỏe, vị ngọt thanh từ nước dừa và thảo dược.","tips":"Không hầm quá lâu để thuốc không bị đắng. Dùng nồi đất hoặc nồi áp suất để giữ dưỡng chất.","calories":320,"time":60},
{"id":"ca-chep-017","name":"Cá chép muối chiên","region":"toan-quoc","difficulty":"de","ingredients":{"main":"1 con cá chép 500g, 50g muối hạt","optional":"Tiêu, chanh, ớt, dầu ăn, rau răm, hành tím"},"steps":["Cá rửa sạch, để thật ráo, ướp muối hạt và tiêu 15 phút.","Chiên cá ngập dầu lửa vừa đến khi da giòn, thịt chín đều.","Vớt ra, cắt miếng, ăn kèm muối tiêu chanh và rau răm."],"tags":["salt-fried","crispy","simple","aromatic","quick"],"description":"Cá muối chiên da giòn rụm, thịt đậm vị mặn tự nhiên, chấm muối tiêu chanh cực kỳ đưa cơm.","tips":"Phơi cá nơi thoáng gió 1 tiếng trước khi chiên để da khô, chiên sẽ giòn lâu hơn.","calories":330,"time":35},
{"id":"ca-chep-018","name":"Cá chép nấu riêu","region":"mien-bac","difficulty":"trung-binh","ingredients":{"main":"1 con cá chép 600g, 200g cua đồng giã","optional":"Cà chua, đậu phụ, mắm tôm, hành lá, thì là, dầu ăn, muối"},"steps":["Lọc nước cua, đun sôi để gạch nổi, vớt riêng. Cá cắt khúc ướp sơ.","Xào cà chua, cho nước cua vào đun, thả đậu phụ rán.","Cho cá vào nấu chín, nêm mắm tôm, rắc thì là, hành lá."],"tags":["crab-paste","rich","traditional","comfort-food","savory"],"description":"Canh riêu cá chép đậm đà, gạch cua béo ngậy hòa quyện vị chua nhẹ từ cà, ăn kèm bún hoặc cơm.","tips":"Khuấy nhẹ khi đun nước cua để gạch không bị lắng. Cho mắm tôm vào sau cùng để giữ mùi thơm.","calories":380,"time":50},
{"id":"ca-chep-019","name":"Cá chép hấp xì dầu","region":"toan-quoc","difficulty":"de","ingredients":{"main":"1 con cá chép 500g, 3 muỗng xì dầu","optional":"Gừng, hành lá, dầu ăn nóng, tiêu trắng, đường, ớt sợi"},"steps":["Cá làm sạch, khứa chéo, ướp xì dầu, đường, gừng băm 15 phút.","Đặt cá lên đĩa, hấp cách thủy 20 phút đến khi chín.","Rắc hành lá, ớt sợi, rưới dầu ăn sôi lên mặt cá."],"tags":["soy-sauce","steamed","umami","light","chinese-inspired"],"description":"Cá hấp xì dầu thanh nhẹ, vị mặn ngọt hài hòa, thịt cá mềm mọng nước, thơm mùi gừng hành.","tips":"Dùng xì dầu loại ngon sẽ không bị mặn gắt. Rưới dầu sôi giúp hành lá chín thơm và dậy mùi.","calories":290,"time":30},
{"id":"ca-chep-020","name":"Cá chép rang me","region":"mien-nam","difficulty":"de","ingredients":{"main":"1 con cá chép 600g, 50g me chín","optional":"Đường, nước mắm, tỏi băm, ớt, dầu ăn, tiêu, hành phi"},"steps":["Cá chiên vàng, vớt ra. Me ngâm nước ấm, lọc bỏ hạt.","Đun me với đường, mắm, tỏi ớt đến khi sánh sệt.","Cho cá vào đảo nhanh tay, nước me bám đều thì tắt bếp."],"tags":["tamarind","sweet-sour","sticky","quick","southern"],"description":"Cá rang me chua ngọt hấp dẫn, lớp sốt me bóng bẩy bám đều từng miếng cá, kích thích vị giác.","tips":"Lọc kỹ me để không bị cặn. Đảo cá nhẹ tay để nước sốt không bị vỡ cá.","calories":340,"time":25},
{"id":"ca-chep-021","name":"Cá chép bọc mỡ chài nướng","region":"mien-trung","difficulty":"kho","ingredients":{"main":"1 con cá chép 500g, 200g mỡ chài","optional":"Sả, ớt, ngũ vị hương, nước mắm, đường, lá lốt, than hoa"},"steps":["Cá ướp sả ớt, ngũ vị hương, mắm đường 20 phút.","Trải mỡ chài, đặt cá lên, gói kín, buộc lạt cố định.","Nướng trên than hoa 25 phút, lật đều đến khi mỡ chài vàng giòn."],"tags":["grilled","pork-lace","crispy","aromatic","traditional"],"description":"Cá bọc mỡ chài nướng giữ độ ẩm tuyệt đối, lớp mỡ ngoài giòn tan, thịt trong mềm ngọt.","tips":"Mỡ chài cần ngâm nước lạnh cho mềm trước khi gói. Nướng lửa đều để mỡ không chảy hết.","calories":420,"time":45},
{"id":"ca-chep-022","name":"Cá chép kho nghệ","region":"toan-quoc","difficulty":"de","ingredients":{"main":"1 con cá chép 500g, 2 củ nghệ tươi","optional":"Nước mắm, đường, tiêu, hành tím, ớt, nước dừa, dầu ăn"},"steps":["Nghệ giã nhuyễn, lọc lấy nước cốt. Cá ướp nghệ, mắm, đường 15 phút.","Phi hành tím, cho cá vào kho lửa nhỏ, thêm nước dừa.","Kho đến khi nước sệt, rắc tiêu, ớt, dùng nóng."],"tags":["turmeric","golden","anti-inflammatory","home-cooking","comfort-food"],"description":"Cá kho nghệ vàng ươm, thơm nồng nghệ tươi, vị đậm đà, tốt cho tiêu hóa và sức khỏe.","tips":"Dùng nghệ tươi sẽ thơm và lên màu đẹp hơn bột nghệ. Kho nhỏ lửa để nghệ không bị đắng.","calories":310,"time":35},
{"id":"ca-chep-023","name":"Cá chép nấu canh măng","region":"mien-bac","difficulty":"trung-binh","ingredients":{"main":"1 con cá chép 600g, 200g măng chua","optional":"Hành khô, thì là, hành lá, nước mắm, muối, tiêu, ớt"},"steps":["Măng rửa nhiều lần, luộc sơ, vắt ráo. Cá cắt khúc ướp muối.","Phi hành khô, xào măng săn, đổ nước đun sôi.","Thả cá vào nấu chín, nêm nếm, rắc thì là, hành lá."],"tags":["bamboo-shoot","sour-soup","northern","traditional","aromatic"],"description":"Canh măng chua nấu cá chép thanh mát, vị chua dịu của măng hòa quyện thịt cá ngọt lành.","tips":"Luộc măng kỹ để loại bỏ độc tố và vị chát. Nêm muối nhẹ vì măng đã chua sẵn.","calories":280,"time":40},
{"id":"ca-chep-024","name":"Cá chép chiên bột xù","region":"mien-nam","difficulty":"trung-binh","ingredients":{"main":"1 con cá chép 500g, 100g bột chiên xù","optional":"Trứng gà, muối, tiêu, chanh, tương ớt, dầu ăn, rau sống"},"steps":["Cá làm sạch, khứa chéo, ướp muối tiêu 10 phút.","Nhúng cá qua trứng đánh tan, lăn đều qua bột chiên xù.","Chiên ngập dầu lửa vừa đến khi vàng giòn, cắt miếng ăn kèm tương."],"tags":["breaded","deep-fried","crispy","quick","snack"],"description":"Cá chiên bột xù giòn rụm bên ngoài, mềm ẩm bên trong, chấm tương ớt ăn kèm rau sống rất vui miệng.","tips":"Dùng chảo sâu lòng để chiên ngập dầu. Lăn bột kỹ để vỏ không bị bong tróc.","calories":370,"time":30},
{"id":"ca-chep-025","name":"Cá chép hấp hành gừng","region":"toan-quoc","difficulty":"de","ingredients":{"main":"1 con cá chép 500g, 50g gừng, 50g hành lá","optional":"Nước tương, dầu ăn, tiêu, muối, đường, ớt lát"},"steps":["Gừng thái sợi, hành lá cắt khúc. Cá ướp muối, gừng, hành 15 phút.","Đặt cá lên đĩa, hấp cách thủy 20 phút.","Pha nước tương, đường, dầu nóng rưới lên cá, rắc tiêu ớt."],"tags":["steamed","ginger","light","simple","healthy"],"description":"Cá hấp hành gừng thanh nhẹ, vị gừng ấm nóng giúp khử tanh, thích hợp ăn vào mùa lạnh.","tips":"Hành gừng nên ngâm nước đá 5 phút trước khi hấp để giữ độ giòn và màu đẹp.","calories":270,"time":25},
{"id":"ca-chep-026","name":"Cá chép om chuối đậu","region":"mien-bac","difficulty":"trung-binh","ingredients":{"main":"1 con cá chép 600g, 3 quả chuối xanh, 2 bìa đậu phụ","optional":"Mẻ, mắm tôm, nghệ, hành lá, thì là, tía tô, dầu ăn"},"steps":["Chuối gọt vỏ, cắt khúc ngâm nước muối. Đậu rán vàng. Cá ướp nghệ, mẻ.","Phi hành, xào chuối săn, đổ nước, nêm mắm tôm, thả cá và đậu.","Om lửa nhỏ 20 phút, rắc tía tô, thì là, hành lá."],"tags":["banana-stem","fermented","rich","northern","comfort-food"],"description":"Cá om chuối đậu đậm đà vị mẻ và mắm tôm, chuối chín mềm bở, đậu phụ thấm nước dùng.","tips":"Dùng chuối xanh vừa tới để không bị nát khi om. Mẻ nên lọc kỹ trước khi nêm.","calories":360,"time":45},
{"id":"ca-chep-027","name":"Cá chép sốt me cay","region":"mien-nam","difficulty":"de","ingredients":{"main":"1 con cá chép 500g, 50g me chín, 10g ớt bột","optional":"Đường, nước mắm, tỏi băm, hành phi, dầu ăn, tiêu, rau răm"},"steps":["Cá chiên vàng, vớt ráo. Me ngâm nước ấm, lọc lấy cốt.","Đun me với đường, mắm, ớt bột, tỏi đến khi sánh.","Cho cá vào đảo nhanh, rắc hành phi, rau răm."],"tags":["spicy","tamarind","sticky","quick","flavorful"],"description":"Cá sốt me cay nồng hấp dẫn, vị chua cay mặn ngọt cân bằng, kích thích vị giác mạnh mẽ.","tips":"Điều chỉnh lượng ớt bột theo khẩu vị. Đảo nhanh tay để cá không vỡ nát and sốt không bị cháy.","calories":350,"time":30},
{"id":"ca-chep-028","name":"Cá chép nấu ngót","region":"mien-trung","difficulty":"de","ingredients":{"main":"1 con cá chép 600g, 200g rau ngót","optional":"Hành khô, nước mắm, muối, tiêu, dầu ăn, gừng, hành lá"},"steps":["Rau ngót tuốt lá, vò nhẹ, rửa sạch. Cá cắt khúc ướp sơ.","Phi hành khô, xào cá săn, đổ nước đun sôi.","Thả rau ngót vào nấu chín, nêm nếm, rắc hành lá."],"tags":["vegetable-soup","light","quick","healthy","traditional"],"description":"Canh cá nấu ngót thanh mát, vị ngọt tự nhiên từ rau và cá, dễ tiêu hóa và giải nhiệt.","tips":"Không nấu rau ngót quá lâu để giữ màu xanh và vitamin. Cho gừng vào khử tanh hiệu quả.","calories":250,"time":25},
{"id":"ca-chep-029","name":"Cá chép kho tiêu","region":"mien-nam","difficulty":"de","ingredients":{"main":"1 con cá chép 500g, 2 muỗng tiêu đen","optional":"Nước mắm, đường, hành tím, ớt, nước dừa, dầu ăn"},"steps":["Cá ướp mắm, đường, tiêu trong 10 phút. Hành tím phi thơm.","Cho cá vào nồi, thêm nước dừa, kho lửa nhỏ.","Đến khi nước sệt, rắc thêm tiêu và ớt, tắt bếp."],"tags":["pepper","savory","home-cooking","caramelized","comfort-food"],"description":"Cá kho tiêu thơm nồng, vị mặn ngọt hài hòa, tiêu đen kích thích vị giác, ăn cơm rất ngon.","tips":"Dùng tiêu nguyên hạt giã rối sẽ thơm hơn tiêu xay sẵn. Kho lửa nhỏ để tiêu không bị đắng.","calories":320,"time":35},
{"id":"ca-chep-030","name":"Cá chép hấp sả","region":"toan-quoc","difficulty":"de","ingredients":{"main":"1 con cá chép 600g, 5 cây sả","optional":"Gừng, hành lá, nước mắm, muối, ớt, chanh, dầu ăn"},"steps":["Sả đập dập, cắt khúc. Gừng thái sợi. Cá ướp sả, gừng, muối 15 phút.","Đặt cá lên đĩa, xếp sả gừng lên trên, hấp cách thủy 25 phút.","Rưới nước mắm chanh ớt, rắc hành lá, dùng nóng."],"tags":["lemongrass","steamed","aromatic","light","refreshing"],"description":"Cá hấp sả thơm mát, hương sả đặc trưng khử tanh hiệu quả, thịt cá ngọt mềm thanh nhẹ.","tips":"Đập dập sả để tinh dầu tiết ra nhiều hơn. Hấp vừa chín tới để thịt không bị khô.","calories":280,"time":30},
{"id":"ca-chep-031","name":"Cá chép chiên tỏi","region":"mien-nam","difficulty":"de","ingredients":{"main":"1 con cá chép 500g, 50g tỏi băm","optional":"Nước mắm, đường, tiêu, chanh, dầu ăn, ớt, hành lá"},"steps":["Cá ướp muối, chiên vàng giòn, vớt ra. Tỏi băm phi vàng thơm.","Pha nước mắm, đường, chanh, tỏi phi, ớt.","Rưới hỗn hợp lên cá, rắc hành lá, thưởng thức ngay."],"tags":["garlic","crispy","quick","aromatic","southern"],"description":"Cá chiên tỏi giòn thơm, vị tỏi vàng béo hòa quyện nước mắm chua ngọt, ăn cực kỳ đưa cơm.","tips":"Phi tỏi lửa nhỏ để tỏi vàng đều mà không bị cháy đắng. Chiên cá thật khô để vỏ giòn lâu.","calories":340,"time":25},
{"id":"ca-chep-032","name":"Cá chép nấu cháo hạt sen","region":"toan-quoc","difficulty":"trung-binh","ingredients":{"main":"1 con cá chép 400g, 50g hạt sen khô, 100g gạo tẻ","optional":"Gừng, hành khô, ngò rí, nước mắm, muối, tiêu, dầu ăn"},"steps":["Nấu gạo và hạt sen thành cháo mềm. Luộc cá, gỡ thịt, xương hầm lấy nước trong.","Xào hành, gừng, phi thơm, cho thịt cá vào đảo nhẹ.","Đổ cá và nước dùng vào cháo, nêm nếm, rắc hành ngò."],"tags":["porridge","lotus-seed","nourishing","calming","breakfast"],"description":"Cháo cá hạt sen thanh mát, vị ngọt dịu, giúp an thần và bồi bổ cơ thể hiệu quả.","tips":"Tâm sen nên bỏ để cháo không bị đắng. Nấu hạt sen mềm kỹ trước khi cho gạo vào.","calories":270,"time":55},
{"id":"ca-chep-033","name":"Cá chép gói lá sen hấp","region":"mien-bac","difficulty":"trung-binh","ingredients":{"main":"1 con cá chép 500g, 2 lá sen tươi","optional":"Gừng, hành tím, nước tương, đường, tiêu, dầu mè, lá lốt"},"steps":["Cá làm sạch, ướp gừng, hành tím, nước tương, đường 15 phút.","Gói cá kín trong lá sen, đặt vào xửng.","Hấp cách thủy 25 phút, rắc tiêu, rưới dầu mè."],"tags":["lotus-leaf","steamed","aromatic","traditional","light"],"description":"Cá gói lá sen hấp giữ trọn hương thơm thanh khiết của sen, thịt cá mềm ngọt, vị nhẹ nhàng.","tips":"Dùng lá sen tươi không bị rách sẽ giữ hương tốt hơn. Lá sen nên rửa sạch và lau khô trước khi gói.","calories":260,"time":35},
{"id":"ca-chep-034","name":"Cá chép rim gừng","region":"mien-trung","difficulty":"de","ingredients":{"main":"1 con cá chép 500g, 30g gừng tươi","optional":"Nước mắm, đường, nước màu, tiêu, ớt, dầu ăn"},"steps":["Gừng thái sợi mỏng. Cá ướp mắm, đường, nước màu, gừng 10 phút.","Cho cá vào nồi, rim lửa nhỏ, trở nhẹ tay.","Khi nước sệt, thêm gừng tươi và ớt, rim thêm 2 phút."],"tags":["ginger","simmered","sweet-savory","warming","home-cooking"],"description":"Cá rim gừng thơm nồng, vị gừng ấm áp cân bằng vị mặn ngọt, thích hợp ăn vào ngày lạnh.","tips":"Cho gừng vào hai lần: ướp để ngấm và rim cuối để dậy mùi. Rim lửa nhỏ để không cháy đáy nồi.","calories":310,"time":30},
{"id":"ca-chep-035","name":"Cá chép nướng than hoa","region":"mien-trung","difficulty":"trung-binh","ingredients":{"main":"1 con cá chép 700g, than hoa","optional":"Muối, tiêu, sả, ớt, chanh, dầu ăn, rau sống, bánh tráng"},"steps":["Cá làm sạch, khứa chéo, ướp muối tiêu, sả ớt 20 phút.","Gá cá lên vỉ, nướng trên than hoa lửa đều.","Nướng 25 phút, lật trở, đến khi da vàng giòn, chấm muối ớt chanh."],"tags":["charcoal","grilled","smoky","street-food","crispy"],"description":"Cá nướng than hoa thơm khói đặc trưng, da giòn thịt ngọt, chấm muối ớt chanh ăn kèm rau sống rất ngon.","tips":"Quét dầu lên vỉ nướng để cá không dính. Than hồng đều giúp cá chín vàng không bị cháy xém.","calories":330,"time":40},
{"id":"ca-chep-036","name":"Cá chép nấu canh khổ qua","region":"mien-trung","difficulty":"trung-binh","ingredients":{"main":"1 con cá chép 600g, 1 quả khổ qua","optional":"Thịt băm, hành khô, nước mắm, muối, tiêu, hạt nêm, hành lá"},"steps":["Khổ qua bổ đôi, bỏ ruột, cắt khúc. Cá cắt khúc ướp sơ.","Phi hành, xào thịt băm, đổ nước đun sôi, thả khổ qua.","Cho cá vào nấu chín, nêm nếm, rắc hành lá."],"tags":["bitter-melon","clear-soup","healthy","traditional","refreshing"],"description":"Canh khổ qua cá chép thanh mát, vị đắng nhẹ giúp thanh nhiệt, thịt cá ngọt lành cân bằng vị.","tips":"Luộc khổ qua qua nước sôi có pha muối để giảm đắng. Nấu lửa vừa để khổ qua không nát.","calories":260,"time":35},
{"id":"ca-chep-037","name":"Cá chép sốt bơ tỏi","region":"mien-nam","difficulty":"de","ingredients":{"main":"1 con cá chép 500g, 50g bơ lạt","optional":"Tỏi băm, hành lá, nước mắm, đường, tiêu, chanh, dầu ăn"},"steps":["Cá chiên vàng, vớt ráo. Bơ đun chảy, phi tỏi thơm.","Cho nước mắm, đường, chanh vào bơ, đun nhẹ đến khi sánh.","Rưới hỗn hợp lên cá, rắc hành lá, tiêu."],"tags":["butter","garlic","rich","quick","western-fusion"],"description":"Cá sốt bơ tỏi béo ngậy, thơm nồng tỏi, vị mặn ngọt hài hòa, lạ miệng và dễ ăn.","tips":"Dùng bơ lạt nguyên chất sẽ thơm hơn bơ thực vật. Không đun bơ quá lửa để không bị cháy khét.","calories":380,"time":25},
{"id":"ca-chep-038","name":"Cá chép kho quẹt","region":"mien-nam","difficulty":"de","ingredients":{"main":"1 con cá chép 400g, 3 muỗng nước mắm","optional":"Đường, tiêu, ớt, hành tím, nước dừa, dầu ăn, bánh tráng nóng"},"steps":["Cá cắt khúc nhỏ, ướp mắm, đường, tiêu 10 phút.","Phi hành, cho cá vào kho, thêm nước dừa, đun lửa nhỏ.","Kho đến khi nước gần cạn, sệt lại, tắt bếp."],"tags":["dipping-sauce","sweet-savory","communal","street-food","traditional"],"description":"Cá kho quẹt mặn ngọt đậm đà, chấm bánh tráng nóng giòn rụm, món ăn vặt dân dã cực kỳ cuốn.","tips":"Kho cạn nước để cá không bị ướt bánh tráng. Dùng bánh tráng nướng sẽ giòn hơn tráng nước.","calories":300,"time":30},
{"id":"ca-chep-039","name":"Cá chép hấp tương hột","region":"mien-trung","difficulty":"de","ingredients":{"main":"1 con cá chép 500g, 3 muỗng tương hột","optional":"Gừng, hành tím, ớt, đường, dầu ăn, hành lá, tiêu"},"steps":["Cá làm sạch, khứa nhẹ, ướp tương hột, đường, gừng 15 phút.","Đặt cá lên đĩa, hấp cách thủy 20 phút.","Phi hành tím, ớt rưới lên mặt cá, rắc hành lá, tiêu."],"tags":["soybean-paste","steamed","savory","traditional","light"],"description":"Cá hấp tương hột thơm bùi, vị mặn nhẹ đặc trưng miền Trung, thịt cá mềm ngọt thanh.","tips":"Tương hột có sẵn vị mặn nên hạn chế thêm gia vị. Hấp kín lửa để hơi nóng giữ ẩm cho cá.","calories":290,"time":30},
{"id":"ca-chep-040","name":"Cá chép chiên giòn sốt chua ngọt","region":"toan-quoc","difficulty":"trung-binh","ingredients":{"main":"1 con cá chép 600g, 50g bột chiên giòn","optional":"Dứa, cà chua, ớt chuông, đường, giấm, nước mắm, tỏi, dầu ăn"},"steps":["Cá ướp muối, lăn bột chiên vàng giòn. Rau củ cắt miếng vừa ăn.","Xào rau củ săn, pha đường, giấm, mắm, tỏi, đun sôi sánh.","Đổ sốt lên cá chiên, dùng nóng."],"tags":["sweet-sour","crispy","colorful","quick","family-meal"],"description":"Cá chiên giòn rụm phủ sốt chua ngọt rau củ tươi mát, màu sắc bắt mắt, dễ ăn cho cả nhà.","tips":"Chiên cá thật khô để sốt không làm ỉu vỏ. Nêm sốt chua ngọt cân bằng trước khi đổ lên cá.","calories":390,"time":35},
{"id":"ca-chep-041","name":"Cá chép nấu canh cải chua","region":"mien-bac","difficulty":"de","ingredients":{"main":"1 con cá chép 500g, 200g cải bẹ xanh muối chua","optional":"Cà chua, hành khô, nước mắm, muối, tiêu, hành lá, dầu ăn"},"steps":["Cải chua rửa sạch, cắt khúc. Cá cắt khúc ướp muối.","Phi hành, xào cải và cà chua, đổ nước đun sôi.","Thả cá vào nấu chín, nêm nếm, rắc hành lá."],"tags":["pickled-vegetable","sour-soup","northern","quick","refreshing"],"description":"Canh cải chua cá chép thanh mát, vị chua dịu của cải hòa quyện thịt cá ngọt, giải nhiệt ngày hè.","tips":"Không nấu cải quá lâu để giữ độ giòn và vitamin. Nêm muối nhẹ vì cải đã mặn sẵn.","calories":260,"time":30},
{"id":"ca-chep-042","name":"Cá chép om dừa","region":"mien-nam","difficulty":"de","ingredients":{"main":"1 con cá chép 500g, 200ml nước cốt dừa","optional":"Sả, gừng, hành tím, nước mắm, đường, tiêu, ớt, rau răm"},"steps":["Cá ướp sả gừng, mắm đường 15 phút. Phi hành tím thơm.","Cho cá vào nồi, đổ nước cốt dừa ngập nửa cá, om lửa nhỏ.","Om 20 phút đến khi nước sệt, rắc rau răm, tiêu."],"tags":["coconut","creamy","rich","southern","comfort-food"],"description":"Cá om dừa béo ngậy, nước dừa ngọt thanh thấm vào thịt cá, vị đậm đà khó quên.","tips":"Dùng nước cốt dừa tươi sẽ thơm hơn đóng hộp. Om lửa nhỏ để nước cốt không bị tách dầu.","calories":350,"time":35},
{"id":"ca-chep-043","name":"Cá chép chưng trứng","region":"toan-quoc","difficulty":"de","ingredients":{"main":"1 con cá chép 400g, 2 quả trứng gà","optional":"Hành lá, gừng, nước mắm, tiêu, dầu ăn, muối, hành tím"},"steps":["Cá hấp chín, gỡ thịt thành miếng nhỏ. Trứng đánh tan with hành, gừng, mắm.","Trộn cá vào trứng, đổ vào đĩa chưng cách thủy 15 phút.","Rắc tiêu, hành phi, dùng nóng with cơm."],"tags":["steamed-egg","soft","nutritious","quick","family-meal"],"description":"Cá chưng trứng mềm mịn, vị ngọt từ cá và trứng hòa quyện, dễ tiêu hóa và giàu dinh dưỡng.","tips":"Đánh trứng nhẹ tay để không bị nhiều bọt. Chưng lửa vừa để trứng mịn không bị rỗ.","calories":290,"time":25},
{"id":"ca-chep-044","name":"Cá chép rang muối ớt","region":"mien-nam","difficulty":"de","ingredients":{"main":"1 con cá chép 500g, 50g muối hạt, 10g ớt bột","optional":"Tỏi băm, chanh, dầu ăn, rau răm, hành tím, tiêu"},"steps":["Cá ướp muối, ớt bột, tỏi 15 phút. Rang cá trong chảo không dầu lửa nhỏ.","Đến khi cá khô săn, muối bám đều, vớt ra.","Cắt miếng, chấm muối ớt chanh, ăn kèm rau răm."],"tags":["salt-roasted","spicy","dry","quick","snack"],"description":"Cá rang muối ớt khô ráo, vị mặn cay thấm đều, chấm chanh tươi rất kích thích vị giác.","tips":"Dùng chảo dày để nhiệt phân bố đều. Rang lửa nhỏ để cá không cháy mà vẫn khô giòn.","calories":320,"time":30},
{"id":"ca-chep-045","name":"Cá chép hấp rượu nếp","region":"mien-bac","difficulty":"trung-binh","ingredients":{"main":"1 con cá chép 600g, 50ml rượu nếp cái hoa vàng","optional":"Gừng, hành tím, nước mắm, đường, tiêu, lá chuối, dầu ăn"},"steps":["Cá làm sạch, ướp gừng, hành, rượu nếp 20 phút.","Gói cá trong lá chuối, đặt vào xửng hấp.","Hấp 25 phút, pha nước mắm đường tiêu rưới lên cá."],"tags":["rice-wine","steamed","aromatic","northern","traditional"],"description":"Cá hấp rượu nếp thơm nồng hương lên men, vị ngọt dịu, khử tanh triệt để, rất đặc sắc.","tips":"Rượu nếp cái hoa vàng sẽ thơm và không gắt. Gói kín lá chuối để hương rượu không bay hơi.","calories":300,"time":35},
{"id":"ca-chep-046","name":"Cá chép kho sả ớt","region":"mien-trung","difficulty":"de","ingredients":{"main":"1 con cá chép 500g, 5 cây sả, 5 quả ớt","optional":"Nước mắm, đường, nước dừa, hành tím, tiêu, dầu ăn"},"steps":["Sả ớt băm nhuyễn. Cá ướp sả ớt, mắm, đường 15 phút.","Phi hành tím, cho cá vào kho, thêm nước dừa.","Kho lửa nhỏ đến khi nước sệt, rắc tiêu."],"tags":["lemongrass","spicy","simmered","central","flavorful"],"description":"Cá kho sả ớt thơm nồng, vị cay nồng sả ớt kích thích vị giác, đậm đà bản sắc miền Trung.","tips":"Dùng sả già sẽ thơm hơn sả non. Kho lửa nhỏ để sả ớt không bị đắng cháy.","calories":310,"time":30},
{"id":"ca-chep-047","name":"Cá chép nấu canh rau răm","region":"toan-quoc","difficulty":"de","ingredients":{"main":"1 con cá chép 500g, 50g rau răm","optional":"Gừng, hành khô, nước mắm, muối, tiêu, dầu ăn, hành lá"},"steps":["Cá cắt khúc, ướp muối gừng. Rau răm nhặt rửa sạch.","Phi hành khô, xào cá săn, đổ nước đun sôi.","Thả rau răm vào nấu chín, nêm nếm, rắc hành lá."],"tags":["vietnamese-coriander","clear-soup","warming","quick","light"],"description":"Canh cá rau răm thanh nhẹ, hương rau răm đặc trưng giúp ấm bụng và khử tanh hiệu quả.","tips":"Cho rau răm vào cuối cùng để giữ hương và màu xanh. Nêm nhạt để vị rau không bị lấn át.","calories":250,"time":20},
{"id":"ca-chep-048","name":"Cá chép chiên giòn chấm tương","region":"mien-nam","difficulty":"de","ingredients":{"main":"1 con cá chép 600g, 50g bột năng","optional":"Tương cà, tương ớt, đường, giấm, tỏi băm, dầu ăn, hành lá"},"steps":["Cá ướp muối, lăn bột năng chiên vàng giòn. Pha tương cà, ớt, đường, giấm, tỏi.","Đun hỗn hợp tương sôi nhẹ, tắt bếp. Cắt cá ra đĩa.","Chấm tương ăn kèm, rắc hành lá lên trên."],"tags":["crispy","sweet-sauce","quick","street-food","simple"],"description":"Cá chiên giòn rụm chấm tương chua ngọt tỏi ớt, món ăn vặt dân dã dễ làm và ngon miệng.","tips":"Lăn bột đều và chiên ngập dầu để cá giòn lâu. Pha tương trước khi chiên cá để tiết kiệm thời gian.","calories":360,"time":25},
{"id":"ca-chep-049","name":"Cá chép hấp nấm đông cô","region":"toan-quoc","difficulty":"de","ingredients":{"main":"1 con cá chép 500g, 50g nấm đông cô khô","optional":"Gừng, hành lá, nước tương, dầu mè, tiêu, muối, đường"},"steps":["Nấm ngâm mềm, cắt sợi. Cá ướp gừng, muối, nước tương 15 phút.","Xếp nấm lên cá, hấp cách thủy 20 phút.","Rắc hành lá, tiêu, rưới dầu mè nóng lên mặt cá."],"tags":["shiitake","steamed","umami","light","healthy"],"description":"Cá hấp nấm đông cô thơm ngon, vị ngọt từ nấm and cá hòa quyện, thanh đạm và bổ dưỡng.","tips":"Ngâm nấm trong nước ấm có chút đường để nấm nở nhanh và giữ hương. Hấp kín lửa để cá không bị khô.","calories":280,"time":30},
{"id":"ca-chep-050","name":"Cá chép kho tộ tiêu xanh","region":"mien-nam","difficulty":"de","ingredients":{"main":"1 con cá chép 500g, 20g tiêu xanh","optional":"Nước mắm, đường, nước dừa, hành tím, ớt, dầu ăn, tía tô"},"steps":["Cá ướp mắm, đường, tiêu xanh giã dập 15 phút.","Phi hành, cho cá vào kho, thêm nước dừa, đun lửa nhỏ.","Kho đến khi nước sệt, rắc tía tô, tiêu xanh nguyên hạt."],"tags":["green-pepper","caramelized","aromatic","southern","comfort-food"],"description":"Cá kho tiêu xanh thơm nồng hương tiêu tươi, vị cay nhẹ thanh mát, thịt cá chắc ngọt thấm gia vị.","tips":"Dùng tiêu xanh tươi sẽ thơm và không gắt như tiêu khô. Kho lửa nhỏ để tiêu không bị đắng cháy.","calories":310,"time":35}
]

# Function to determine category and subCategory
# Styles: kho, hap, canh, chien, om, chao, nuong, rim, lau, xao, chung, cuon, rang, hầm, nấu ngót, sốt, nấu riêu
def get_cats(name, tags):
    name_low = name.lower()
    sub = "khac"
    cat = "com"
    
    if "kho" in name_low or "rim" in name_low or "quẹt" in name_low:
        sub = "kho"
    elif "hấp" in name_low or "hầm" in name_low or "chưng" in name_low:
        sub = "hap"
    elif "canh" in name_low or "riêu" in name_low or "ngót" in name_low:
        sub = "canh"
    elif "chiên" in name_low or "rang" in name_low:
        sub = "chien"
    elif "om" in name_low:
        sub = "kho" # or om if exists
    elif "cháo" in name_low:
        cat = "pho-bun"
        sub = "nuoc"
    elif "nướng" in name_low:
        sub = "nuong"
    elif "lẩu" in name_low:
        cat = "pho-bun"
        sub = "nuoc"
    elif "cuốn" in name_low:
        cat = "an-vat"
        sub = "tron"
    elif "xào" in name_low:
        sub = "xao"
    elif "sốt" in name_low:
        sub = "sot"
        
    return cat, sub

# Transform
processed = []
for r in new_recipes_raw:
    cat, sub = get_cats(r["name"], r["tags"])
    
    main_ing = [i.strip() for i in r["ingredients"]["main"].split(",")]
    opt_ing = [i.strip() for i in r["ingredients"]["optional"].split(",")]
    
    recipe = {
        "id": r["id"],
        "name": r["name"],
        "category": cat,
        "subCategory": sub,
        "ingredients": {
            "main": main_ing,
            "optional": opt_ing
        },
        "steps": r["steps"],
        "cookingTime": r["time"],
        "difficulty": r["difficulty"],
        "servings": 4, # Default
        "tags": r["tags"],
        "region": r["region"],
        "calories": r["calories"],
        "tips": r["tips"],
        "description": r["description"]
    }
    processed.append(recipe)

# Merge
with open(FILE_PATH, 'r', encoding='utf-8') as f:
    existing = json.load(f)

# Append new ones
existing.extend(processed)

# Write back
with open(FILE_PATH, 'w', encoding='utf-8') as f:
    json.dump(existing, f, ensure_ascii=False, indent=2)

print(f"Successfully added {len(processed)} recipes.")
